#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GEMFILES_DIR="${DIR}/gemfiles"
USAGE="Usage: $0 [appraisal-name] COMMAND"

if [ "$#" == "0" ]; then
    echo "$USAGE"
    echo "Appraisals:"
    find $GEMFILES_DIR/*.gemfile | sed -n 's/.*\/\(.*\)\.gemfile/ * \1/p'
    exit 1
fi

if [ -f "$GEMFILES_DIR/$1.gemfile" ]
then
    BUNDLE_GEMFILE="$GEMFILES_DIR/$1.gemfile"
    shift 1

    echo
    echo ">> BUNDLE_GEMFILE=$BUNDLE_GEMFILE $@"
    echo

    BUNDLE_GEMFILE=$BUNDLE_GEMFILE $@
else
    for BUNDLE_GEMFILE in $GEMFILES_DIR/*.gemfile
    do
        echo
        echo ">> BUNDLE_GEMFILE=$BUNDLE_GEMFILE $@"
        echo

        BUNDLE_GEMFILE=$BUNDLE_GEMFILE $@
    done
fi